name: CI

on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    # Security note: pin third-party actions to a full commit SHA to make
    # workflows immutable and satisfy security scanners. See
    # `scripts/ci/list_unpinned_actions.sh` for a helper that lists unpinned
    # actions and suggests API commands to resolve SHAs.
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: scripts/ci/validate.sh
