[package]
name = "count_lines_usecase"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
count_lines_shared_kernel.workspace = true
count_lines_domain.workspace = true
count_lines_ports.workspace = true
chrono.workspace = true
